[theme]
theme = "semi-native"

[icons]
icons = "awesome4"

[[block]]
block = "net"
format = " $icon ^icon_net_down$speed_down.eng(prefix:K) ^icon_net_up$speed_up.eng(prefix:K) "
format_alt = " $icon ^icon_net_down$graph_down ^icon_net_up$graph_up "

[[block]]
block = "disk_space"
path = "/"
info_type = "free"
alert_unit = "GB"
interval = 20
warning = 15.0
alert = 10.0
format = " $icon $free.eng(w:2) "
format_alt = " $icon $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "battery"
format = " $icon\u00A0 $percentage "
missing_format = ""
device = "DisplayDevice"
driver = "upower"

[[block]]
block = "rofication"
interval = 1
socket_path = "/tmp/rofi_notification_daemon"
[[block.click]]
button = "left"
cmd = "ilia -p notifications"

[[block]]
block = "sound"
driver = "pulseaudio"

[[block.click]]
button = "left"
cmd = "regolith-control-center sound"

[[block]]
block = "time"
interval = 5
format = "$icon $timestamp.datetime(f:'%R')"
