theme = "semi-native"
icons = "awesome"

[[block]]
block = "net"

[[block]]
block = "disk_space"
path = "/"
info_type = "free"
format = "{icon} {percentage}"
unit = "GB"
alert = 10
warning = 15
interval = 300

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "battery"
format = " {percentage}"
full_format = " {percentage}"
hide_missing = true
driver = "upower"

[[block]]
block = "rofication"
interval = 5
socket_path = "/tmp/rofi_notification_daemon"

[[block]]
block = "sound"
driver = "pulseaudio"

[[block]]
block = "time"
interval = 5
format = "%R"

